name: Bare Minimum Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  bare-minimum:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk
        export ANDROID_HOME=/usr/lib/android-sdk
        export ANDROID_SDK_ROOT=/usr/lib/android-sdk
        echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/usr/lib/android-sdk" >> $GITHUB_ENV
    
    - name: Build
      run: |
        chmod +x gradlew
        export GRADLE_OPTS="-Xmx512m"
        ./gradlew assembleDebug --no-daemon --offline || ./gradlew assembleDebug --no-daemon
    
    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: bare-minimum-apk
        path: app/build/outputs/apk/debug/app-debug.apk