name: Build Kotlin Simple Keyboard

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        
    - name: Accept Android SDK licenses
      run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-
          
    - name: Clean Gradle
      run: |
        rm -rf ~/.gradle/caches
        rm -rf .gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Check Gradle wrapper
      run: |
        echo "Gradle wrapper version:"
        ./gradlew --version
        echo "Java version:"
        java -version
        echo "Android SDK location:"
        echo $ANDROID_SDK_ROOT
        
    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace --info
        
    - name: List APK files
      run: find . -name "*.apk" -type f
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: simple-keyboard-kotlin-apk-${{ github.sha }}
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Get APK size
      run: |
        APK_SIZE=$(stat -c%s app/build/outputs/apk/debug/app-debug.apk)
        APK_SIZE_MB=$((APK_SIZE / 1024 / 1024))
        echo "APK Size: ${APK_SIZE_MB}MB (${APK_SIZE} bytes)"
        echo "APK_SIZE=${APK_SIZE}" >> $GITHUB_ENV
        echo "APK_SIZE_MB=${APK_SIZE_MB}" >> $GITHUB_ENV
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/debug/app-debug.apk
        name: Simple Keyboard Kotlin ${{ github.ref_name }}
        body: |
          ## 📱 Simple Keyboard Kotlin APK
          
          Современная нативная версия на Kotlin с Jetpack Compose.
          
          ### 📊 Характеристики:
          - 📦 Размер APK: ${{ env.APK_SIZE_MB }}MB
          - ⚡ Производительность: 100% нативная
          - 🎨 UI: Jetpack Compose
          - 🔧 Язык: Kotlin
          
          ### 🚀 Установка:
          1. Скачайте `app-debug.apk`
          2. Установите на Android устройство
          3. Включите клавиатуру в настройках системы
          4. Покажите плавающую кнопку
          
          ### ✨ Функции:
          - ⌨️ InputMethodService
          - 🔘 Плавающая кнопка Enter с перетаскиванием
          - 🐛 Debug сервер с логами в реальном времени
          - 🎨 Material Design 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}