name: Step by Step Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  step-by-step:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Step 1: Checkout"
      uses: actions/checkout@v4
    
    - name: "Step 2: Setup Java"
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: "Step 3: Verify Java"
      run: |
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
    
    - name: "Step 4: Setup Android SDK"
      run: |
        # Manual Android SDK setup
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        
        # Download command line tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools latest
        
        # Set environment variables
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
    
    - name: "Step 5: Install Android components"
      run: |
        # Accept licenses
        yes | sdkmanager --licenses
        
        # Install required components
        sdkmanager "platforms;android-34"
        sdkmanager "build-tools;34.0.0"
        sdkmanager "platform-tools"
        
        # Verify installation
        sdkmanager --list_installed
    
    - name: "Step 6: Prepare Gradle"
      run: |
        chmod +x gradlew
        ./gradlew --version
    
    - name: "Step 7: Clean project"
      run: ./gradlew clean --no-daemon
    
    - name: "Step 8: Build APK"
      run: ./gradlew assembleDebug --no-daemon --stacktrace
    
    - name: "Step 9: Verify APK"
      run: |
        if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
          echo "✅ APK created successfully!"
          ls -lh app/build/outputs/apk/debug/app-debug.apk
        else
          echo "❌ APK not found"
          find . -name "*.apk" -type f
          exit 1
        fi
    
    - name: "Step 10: Upload APK"
      uses: actions/upload-artifact@v4
      with:
        name: step-by-step-apk
        path: app/build/outputs/apk/debug/app-debug.apk