name: Ultra Simple Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
    
    - name: Install SDK components
      run: |
        echo "=== Installing required SDK components ==="
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses <<< 'y'
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-34"
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"
        echo "=== SDK components installed ==="
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --list_installed
    
    - name: Build APK
      run: |
        chmod +x gradlew
        unset GRADLE_OPTS
        unset JAVA_OPTS
        export GRADLE_OPTS="-Xmx1024m -Dfile.encoding=UTF-8"
        echo "=== Starting build ==="
        ./gradlew assembleDebug --no-daemon --stacktrace
        echo "=== Build completed ==="
        find . -name "*.apk" -type f
    
    - uses: actions/upload-artifact@v4
      with:
        name: ultra-simple-apk
        path: app/build/outputs/apk/debug/app-debug.apk